owner: corpuscom
repo: status

sites:
  - name: Corpuscom
    url: https://corpuscom.hu
  - name: Lector
    url: https://lector.hu

status-website:
  baseUrl: /status
  logoUrl: https://corpuscom.hu/img/cc_logo.png
  name: Status
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
