owner: corpuscom
repo: status

sites:
  - name: Corpuscom
    url: https://corpuscom.hu
  - name: Lector
    url: https://lector.hu

status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
